version: 0.0
os: linux
files:
  - source: docker-compose-lowcost.yml
    destination: /home/ubuntu/app
  - source: scripts/start_server.sh
    destination: /home/ubuntu/app/scripts
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
