steps:
  # 1. Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/tenant-repo/backend:$BUILD_ID', './backend']

  # 2. Build Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/tenant-repo/frontend:$BUILD_ID', './frontend']

  # 3. Push Images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/tenant-repo/backend:$BUILD_ID']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/tenant-repo/frontend:$BUILD_ID']

  # 4. Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tenant-backend'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/tenant-repo/backend:$BUILD_ID'
      - '--region'
      - '${_REGION}'

  # 5. Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tenant-frontend'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/tenant-repo/frontend:$BUILD_ID'

      - '--region'
      - '${_REGION}'

substitutions:
  _REGION: us-central1
